---
version: "3"

services:
  docker:
    container_name: docker
    environment:
      DOCKER_TLS_CERTDIR: ""
    image: docker:18-dind
    privileged: true

  grype:
    container_name: grype
    depends_on:
      - docker
    environment:
      DOCKER_HOST: tcp://docker:2375
      DOCKER_PASSWORD: "${DOCKER_PASSWORD-}"
      DOCKER_USERNAME: "${DOCKER_USERNAME-}"
      IMAGE_NAME: hello-world:latest
    image: ghcr.io/cbdq-io/docker-grype:latest
    volumes:
      # This will persist the Grype DB so that it will
      # not need to be downloaded for each invocation.
      - grype_db:/root/.cache/grype

volumes:
  grype_db:
