---
version: "3"

services:
  docker:
    container_name: docker
    environment:
      DOCKER_TLS_CERTDIR: ""
    image: docker:18-dind
    privileged: yes
    volumes:
      - certs:/certs/client
      - ../..:/work
    working_dir: /work

  grype:
    container_name: grype
    depends_on:
      - docker
    environment:
      DOCKER_HOST: tcp://docker:2375
      DOCKER_TLS_CERTDIR: ""
      IMAGE_NAME: hello-world:latest
    image: docker-grype:latest

volumes:
  certs:
