---
version: "3"

services:
  # docker:
  #   container_name: docker
  #   environment:
  #     DOCKER_TLS_CERTDIR: ""
  #   image: docker:18-dind
  #   privileged: yes
  #   volumes:
  #     - certs:/certs/client

  grype:
    build:
      context: ../docker-grype
    command: sleep infinity
    # environment:
    #   DOCKER_HOST: tcp://docker:2375
    #   DOCKER_TLS_CERTDIR: "/certs/client"
    image: docker-grype:latest
    volumes:
      - certs:/certs/client

  sut:
    build:
      context: ../sut
    depends_on:
      # - docker
      - grype
    # environment:
    #   DOCKER_HOST: tcp://docker:2375
    #   DOCKER_TLS_CERTDIR: "/certs/client"
    volumes:
      - certs:/certs/client
      - ..:/work

volumes:
  certs:
