---
name: CD

on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.1.0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Requirements
        run: pip install -r requirements.txt

      - name: Push
        run: make build test push_latest

      - name: Create Tag
        run: |
          make tag
          git push --tags
        # TODO correct how to pick up the tag number.
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
