---
name: CI

on:
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - scenario: A
          - scenario: B
          - scenario: C
          - scenario: D

    steps:
      - uses: actions/checkout@v3.1.0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Requirements
        run: |
          pip install -qr requirements.txt
          pip freeze
          pip check

      - name: Lint
        run: make lint

      - name: Bandit Analyzer
        run: bandit --ini setup.cfg -r .

      - name: ShellCheck
        uses: bewuethr/shellcheck-action@v2

      - name: Docker Version
        run: docker --version

      - name: Build
        run: make build

      - name: Test
        env:
          SCENARIO: "${{ matrix.scenario }}"
        run: |
          echo "This is scenario ${SCENARIO}."
          make test-gh

      - name: Publish Code Coverage
        uses: paambaati/codeclimate-action@v3.2.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: coverage xml
          coverageLocations: |
            ${{github.workspace}}/coverage.xml:coverage.py

  push:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v3.1.0

      - name: Log in to the Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push
        run: make build push_unstable
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/develop' }}
