---
name: CI

on:
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - scenario: A
          - scenario: B
          - scenario: C
          - scenario: D

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Requirements
        run: |
          pip install -qr requirements.txt
          pip freeze

      - name: Lint
        run: make lint

      - name: Bandit Analyzer
        run: bandit -r .

      - name: ShellCheck
        uses: ludeeus/action-shellcheck@master

      - name: Build
        run: make build

      - name: Test
        env:
          SCENARIO: "${{ matrix.scenario }}"
        run: |
          echo "This is scenario ${SCENARIO}."
          make test-gh

      - name: Publish Code Coverage
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: coverage xml
          coverageLocations: |
            ${{github.workspace}}/coverage.xml:coverage.py
