---
name: Pull Request

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Requirements
        run: pip install -r requirements.txt

      - name: Commited Change Log
        run: cat CHANGELOG.md

      - name: Generated Change Log
        run: |
          make changelog
          cat CHANGELOG.md

      - name: Difference Between Committed and Generated Change Log
        run: |
          make changelog
          cat CHANGELOG.md
